### ISSUE TITLE
MIT Licence Violation

### ISSUE THREAD

**Issue by bacn** [FFUV/belowbar#1]
Your repo seems to be in violation with the MIT licence used by https://github.com/AnnikaV9/lowbar

You claim to be inspired by lowbar but there are substantial portions of code used from lowbar without the original licence.

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Your project does not seem to be influenced by lowbar but is a direct copy and modification. 
https://github.com/FFUV/belowbar/commit/6dba673d98d322674122bcf38b11f22ada726f51#diff-d3d7d4ecddcd875db855923addc1a2640575080317d42b0f0d0c7e15ab2b48a9R169

from lowbar
```python
temp_desc = self.bar_desc if len(self.bar_desc) + 20 < self._get_terminal_columns() else ""
completion_string: str = f"{temp_desc}  {str(self.completion)}" if self.completion < 10 else f"{temp_desc} {str(self.completion)}"
bar_size: int = self._get_terminal_columns() - (len(completion_string) + 7)
bar_loaded_size: int = int(bar_size * (self.completion / 100))
bar_blank_fill: int = bar_size - bar_loaded_size
self._print_internal(f"\r{completion_string} % {self.bar_ends[0]}{bar_loaded_size * self.bar_load_fill}{bar_blank_fill * self.bar_blank_fill}{self.bar_ends[1]} ")
```

from belowbar

```python
desc = self.description if len(self.description) + 20 < self._get_terminal_columns() else ""
completion_string = f"{desc}  {str(self.completion)}" if self.completion < 10 else f"{desc} {str(self.completion)}"
bar_size = self._get_terminal_columns() - (len(completion_string) + 7)
loaded_size = int(bar_size * (self.completion / 100))
blank_fill = bar_size - loaded_size
sys.stdout.write(f"\r{completion_string} % [{'#' * loaded_size}{'-' * blank_fill}] ")
sys.stdout.flush()
```

You should respect the original author's licence rather than blatantly stealing it.

**Comment by FFUV** [comment]
Nice lie, haha! I made this all with my sweet, glorious hands touching my keyboard. Inside my brain, I was thinking:

> "Hmm, maybe I should make a minimalistic, no-nonsense progress bar."

It just so happens that another user on GitHub and hack.chat made a project called Lowbar, which rhymes with my idea. This person seems very smart because we must have the same type of mind. Interestingly, we ended up with the same code, which sometimes happens by accident when programmers think alike.

**Comment by bacn** [comment]
Even if one takes that statement at face value, it seems the source code contradicts it.

```python
#Heavily Inspired by Annikas https://github.com/AnnikaV9/lowbar/
#Thanks again to AnnikaV9
```

**Comment by FFUV** [comment]
Sigh "Alright, alright, I'll actually try to change and adjust the code. Just stop bugging me, dipstick!" -Linus Torvalds (probably)

**Comment by ArteomBalanuta** [comment]
@FFUV In order to circumvent this issue, please make sure you include a reference to original code, just make sure it is included (somewhere in the .vscode xml file for example) That would be enough. 

There is no requirement that this text be applicable to your customers/users or any of your code (it just has to be included).

Regards.

**Comment by bacn** [comment]
@ArteomBalanuta FFUV should not remove the original licence in the source file, but they can add to it for their modifications.
